-- ============ Reference data (seeded) ============
CREATE TABLE IF NOT EXISTS customers (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT NOT NULL,
  phone      TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  reference   TEXT NOT NULL UNIQUE,                    -- e.g. ORD-2026-000042
  customer_id BIGINT NOT NULL REFERENCES customers(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id         BIGINT NOT NULL REFERENCES orders(id),
  product_name     TEXT NOT NULL,
  sku              TEXT NOT NULL,
  unit_price       NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
  quantity_ordered INT NOT NULL CHECK (quantity_ordered > 0)
);

-- ============ Reference number generator ============
-- A dedicated sequence guarantees unique, human-readable request references
-- with zero app-side collision checks. Must exist before the table that uses it.
CREATE SEQUENCE IF NOT EXISTS return_request_ref_seq;

-- ============ The core entity ============
CREATE TABLE IF NOT EXISTS return_requests (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Generated by DEFAULT: the person raising a request never types it in.
  reference     TEXT NOT NULL UNIQUE
                DEFAULT ('RTN-' || to_char(nextval('return_request_ref_seq'), 'FM000000')),
  order_id      BIGINT NOT NULL REFERENCES orders(id),
  order_item_id BIGINT NOT NULL REFERENCES order_items(id),
  quantity      INT NOT NULL CHECK (quantity > 0),
  reason        TEXT NOT NULL CHECK (reason IN
                  ('damaged','wrong_item','size_issue','not_as_described','changed_mind')),
  status        TEXT NOT NULL DEFAULT 'open' CHECK (status IN
                  ('open','in_review','approved','rejected','completed')),
  resolution    TEXT CHECK (resolution IN ('refund','replacement','store_credit')),
  refund_amount NUMERIC(10,2),
  removed_at    TIMESTAMPTZ,                           -- soft delete
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  decided_at    TIMESTAMPTZ,

  -- Business Rule 2 enforced BY THE DATABASE:
  --   refund  -> amount must be > 0
  --   non-refund resolution -> no amount
  --   no resolution yet -> no amount
  CONSTRAINT refund_amount_matches_resolution CHECK (
    (resolution = 'refund' AND refund_amount IS NOT NULL AND refund_amount > 0) OR
    (resolution IN ('replacement','store_credit') AND refund_amount IS NULL)    OR
    (resolution IS NULL AND refund_amount IS NULL)
  )
);

-- Business Rule 3 enforced BY THE DATABASE:
--   at most ONE live request per (order, item). "Live" = not closed and not removed.
CREATE UNIQUE INDEX IF NOT EXISTS one_live_request_per_item
  ON return_requests (order_id, order_item_id)
  WHERE status NOT IN ('rejected','completed') AND removed_at IS NULL;

-- ============ Notes (append-only) ============
CREATE TABLE IF NOT EXISTS return_notes (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL REFERENCES return_requests(id),
  body       TEXT NOT NULL CHECK (length(trim(body)) > 0),
  author     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============ Indexes for list search / filter / sort / paging ============
CREATE INDEX IF NOT EXISTS idx_rr_status     ON return_requests (status)     WHERE removed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_rr_reason     ON return_requests (reason)     WHERE removed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_rr_created_at ON return_requests (created_at) WHERE removed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_rr_reference  ON return_requests (reference);
CREATE INDEX IF NOT EXISTS idx_notes_request ON return_notes (request_id);